tap 'caskroom/cask'
tap 'homebrew/bundle'
tap caskroom/fonts

brew 'mas'
brew 'brew-cask'
brew 'emacs'
brew 'bash'
brew 'mysql'
brew 'ansible'
brew 'curl'
brew 'wget'
brew 'git'
brew 'httpie'
brew 'tree'
brew 'tmux'
brew 'youtube-dl'
brew 'terminal-notifier'
brew 'android-sdk'
brew 'awscli'

cask 'phpstorm'
cask 'google-chrome-canary'
cask 'google-chrome'
cask 'coteditor'
cask 'pomodone'
cask 'atom'
cask 'textwrangler'
cask 'android-file-transfer'
cask 'android-studio'
cask 'genymotion'
cask 'java'
cask 'appcleaner'
cask 'vivaldi-snapshot'
cask 'caffeine'
cask 'docker'
cask 'google-japanese-ime'
cask 'google-play-music-desktop-player'
cask 'google-drive'
cask 'amazon-drive'
cask 'dropbox'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'bathyscaphe'
cask 'karabiner-elements'
cask 'hammerspoon'
cask 'postman'
cask 'rescuetime'
cask 'vlc'
cask 'firefoxdeveloperedition-ja'
cask 'font-source-code-pro'
cask 'monolingual'

mas 'LINE', id: 539883307
mas 'Wunderlist', id: 410628904
mas 'Bear', id: 1091189122
mas 'BetterSnapTool', id: 417375580